version: '3'

services:
  app:
    build:
      context: .
    working_dir: '/app'
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/.last_report_id:/app/.last_report_id:rw"
